version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8081:80"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: labrootpassword
      MYSQL_DATABASE: labdatabase
      MYSQL_USER: labuser
      MYSQL_PASSWORD: labpassword
    ports:
      - "3307:3306"
