version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8082:80"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: devrootpassword
      MYSQL_DATABASE: devdatabase
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
    ports:
      - "3308:3306"
